// Generated by CoffeeScript 1.8.0
(function() {
  var getBullshit, http, jquery, jsdom, number;

  jquery = require('jquery');

  jsdom = require('jsdom');

  http = require('http');

  number = 1;

  http.createServer(function(req, res) {
    return getBullshit(1, function(errors, result) {
      if (errors == null) {
        res.writeHead(200, {
          'Content-Type': 'text/plain'
        });
        return res.end(result);
      } else {
        return res.writeHead(500);
      }
    });
  }).listen(process.env.PORT || 3000);

  getBullshit = function(number, done) {
    return jsdom.env('http://cbsg.sourceforge.net/cgi-bin/live', function(errors, window) {
      var $;
      if (errors == null) {
        $ = jquery(window);
        return done(null, $("li").slice(0, number).text());
      } else {
        return done(errors, null);
      }
    });
  };

}).call(this);
