// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, getBullshit, jquery, jsdom, number;

  jquery = require('jquery');

  jsdom = require('jsdom');

  express = require('express');

  app = express();

  number = 1;

  app.get('/', function(req, res) {
    return getBullshit(1, function(errors, result) {
      if (errors == null) {
        return res.status(200).send(result);
      } else {
        return res.status(500).send("error");
      }
    });
  });

  app.listen(process.env.PORT || 3000);

  getBullshit = function(number, done) {
    return jsdom.env('http://cbsg.sourceforge.net/cgi-bin/live', function(errors, window) {
      var $;
      if (errors == null) {
        $ = jquery(window);
        return done(null, $("li").slice(0, number).text());
      } else {
        return done(errors, null);
      }
    });
  };

}).call(this);
